const DB_KEY='perpusku_offline_v1';
const seed={books:[
{id:'B001',title:'Laskar Pelangi',author:'Andrea Hirata',category:'Novel',year:2005,isbn:'9789793062792',stock:4},
{id:'B002',title:'Bumi Manusia',author:'Pramoedya Ananta Toer',category:'Novel',year:1980,isbn:'9789799731234',stock:3},
{id:'B003',title:'Matematika SMP Kelas IX',author:'Dewi Lestari',category:'Pelajaran',year:2023,isbn:'9786231234567',stock:6},
{id:'B004',title:'IPA Terpadu Kelas VIII',author:'Tim Edukasi',category:'Pelajaran',year:2022,isbn:'9786237654321',stock:5},
{id:'B005',title:'Ensiklopedia Sains Anak',author:'Pustaka Cendekia',category:'Referensi',year:2021,isbn:'9786029876543',stock:2}
],loans:[
{id:'L001',bookId:'B001',student:'Alya Putri',className:'IX A',date:'2026-09-01',due:'2026-09-08',returned:false,returnDate:''},
{id:'L002',bookId:'B003',student:'Raka Pratama',className:'VIII B',date:'2026-08-29',due:'2026-09-05',returned:false,returnDate:''},
{id:'L003',bookId:'B004',student:'Nabila Sari',className:'VIII A',date:'2026-08-25',due:'2026-09-01',returned:false,returnDate:''}
]};
function load(){try{return JSON.parse(localStorage.getItem(DB_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
let db=load();function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))} save();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=d=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'));
const today=()=>new Date().toISOString().slice(0,10);
const bookById=id=>db.books.find(b=>b.id===id);
function usedCopies(bookId){return db.loans.filter(l=>l.bookId===bookId&&!l.returned).length}
function available(book){return Math.max(0,book.stock-usedCopies(book.id))}
function isLate(l){return !l.returned && l.due<today()}
function stats(){let total=db.books.reduce((a,b)=>a+b.stock,0), availableTotal=db.books.reduce((a,b)=>a+available(b),0), active=db.loans.filter(l=>!l.returned).length, late=db.loans.filter(isLate).length; return {total,availableTotal,active,late}}
function renderDashboard(){const s=stats();$('#statsGrid').innerHTML=[['Total Buku',s.total,'📚','Semua eksemplar'],['Tersedia',s.availableTotal,'✅','Siap dipinjam'],['Sedang Dipinjam',s.active,'🔄','Belum kembali'],['Terlambat',s.late,'⏰','Perlu ditindaklanjuti']].map(x=>`<div class="stat"><div class="stat-top"><div><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-note">${x[3]}</div></div><div class="stat-icon">${x[2]}</div></div></div>`).join('');
let recent=[...db.loans].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('#recentLoans').innerHTML=recent.length?`<table class="data-table"><thead><tr><th>Siswa</th><th>Buku</th><th>Tanggal</th><th>Status</th></tr></thead><tbody>${recent.map(l=>{let b=bookById(l.bookId);return `<tr><td><b>${esc(l.student)}</b><div class="book-sub">${esc(l.className)}</div></td><td>${esc(b?.title||'-')}</td><td>${fmt(l.date)}</td><td>${statusBadge(l)}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Belum ada data peminjaman.</div>';
let cats={};db.books.forEach(b=>cats[b.category]=(cats[b.category]||0)+b.stock);let max=Math.max(1,...Object.values(cats));$('#collectionSummary').innerHTML=Object.entries(cats).map(([k,v])=>`<div class="summary-row"><span>${esc(k)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('');}
function statusBadge(l){return l.returned?'<span class="badge badge-blue">Dikembalikan</span>':isLate(l)?'<span class="badge badge-red">Terlambat</span>':'<span class="badge badge-green">Dipinjam</span>'}
function renderBooks(){let q=($('#bookSearch').value||'').toLowerCase(),cat=$('#bookCategoryFilter').value;let rows=db.books.filter(b=>(!cat||b.category===cat)&&[b.title,b.author,b.isbn,b.id].some(v=>String(v).toLowerCase().includes(q)));$('#booksTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Kode</th><th>Judul Buku</th><th>Kategori</th><th>Tahun</th><th>Stok</th><th>Tersedia</th><th>Aksi</th></tr></thead><tbody>${rows.map(b=>`<tr><td><b>${b.id}</b></td><td><div class="book-title">${esc(b.title)}</div><div class="book-sub">${esc(b.author)} • ISBN ${esc(b.isbn||'-')}</div></td><td><span class="badge badge-blue">${esc(b.category)}</span></td><td>${b.year||'-'}</td><td>${b.stock}</td><td><span class="badge ${available(b)>0?'badge-green':'badge-red'}">${available(b)}</span></td><td><div class="actions"><button class="icon-btn" data-edit-book="${b.id}">✎</button><button class="icon-btn danger" data-delete-book="${b.id}">🗑</button></div></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Buku tidak ditemukan.</div>';}
function renderLoans(){let q=($('#loanSearch').value||'').toLowerCase(),f=$('#loanStatusFilter').value;let rows=db.loans.filter(l=>{let b=bookById(l.bookId);let text=[l.student,l.className,b?.title].join(' ').toLowerCase();let match=!q||text.includes(q);let st=f===''?true:f==='active'?(!l.returned&&!isLate(l)):f==='returned'?l.returned:f==='late'?isLate(l):true;return match&&st}).sort((a,b)=>b.date.localeCompare(a.date));$('#loansTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Siswa</th><th>Buku</th><th>Pinjam</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(l=>{let b=bookById(l.bookId);return `<tr><td><b>${esc(l.student)}</b><div class="book-sub">${esc(l.className)}</div></td><td>${esc(b?.title||'-')}</td><td>${fmt(l.date)}</td><td>${fmt(l.due)}</td><td>${statusBadge(l)}</td><td>${!l.returned?`<button class="icon-btn" data-return="${l.id}">↩ Kembalikan</button>`:'—'}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Belum ada data peminjaman.</div>'}
function renderReturns(){let active=db.loans.filter(l=>!l.returned).sort((a,b)=>(a.due>b.due?1:-1));$('#returnCards').innerHTML=active.length?active.map(l=>{let b=bookById(l.bookId);return `<div class="return-card"><h3>${esc(b?.title||'-')}</h3><div class="return-meta">Dipinjam oleh <b>${esc(l.student)}</b> (${esc(l.className)})</div><div class="row"><span>Tanggal pinjam</span><b>${fmt(l.date)}</b></div><div class="row"><span>Jatuh tempo</span><b>${fmt(l.due)}</b></div><div class="row"><span>Status</span>${statusBadge(l)}</div><button class="btn btn-primary" data-return="${l.id}">Proses Pengembalian</button></div>`}).join(''):'<div class="panel" style="grid-column:1/-1"><div class="empty">Tidak ada buku yang sedang dipinjam. 🎉</div></div>'}
function refresh(){renderDashboard();populateCategories();renderBooks();renderLoans();renderReturns()}
function populateCategories(){let cats=[...new Set(db.books.map(b=>b.category))].sort(),sel=$('#bookCategoryFilter'),cur=sel.value;sel.innerHTML='<option value="">Semua kategori</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');sel.value=cur}
function showModal(title,sub,body){$('#modalContent').innerHTML=`<h3>${title}</h3><p>${sub}</p>${body}`;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function bookForm(b={}){showModal(b.id?'Edit Buku':'Tambah Buku','Isi data buku di bawah ini.',`<form id="bookForm"><div class="form-grid"><div class="form-field"><label>Kode Buku</label><input name="id" required value="${esc(b.id||'B'+String(Date.now()).slice(-4))}" ${b.id?'readonly':''}></div><div class="form-field"><label>Judul Buku</label><input name="title" required value="${esc(b.title||'')}"></div><div class="form-field"><label>Penulis</label><input name="author" required value="${esc(b.author||'')}"></div><div class="form-field"><label>Kategori</label><input name="category" required value="${esc(b.category||'Novel')}"></div><div class="form-field"><label>Tahun Terbit</label><input name="year" type="number" min="1900" max="2100" value="${b.year||new Date().getFullYear()}"></div><div class="form-field"><label>ISBN</label><input name="isbn" value="${esc(b.isbn||'')}"></div><div class="form-field full"><label>Jumlah Stok</label><input name="stock" type="number" min="0" required value="${b.stock??1}"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" id="cancelModal">Batal</button><button class="btn btn-primary">Simpan Buku</button></div></form>`);$('#bookForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),data=Object.fromEntries(fd);data.stock=Number(data.stock);data.year=Number(data.year);if(b.id){Object.assign(b,data)}else{if(db.books.some(x=>x.id===data.id))return toast('Kode buku sudah digunakan.');db.books.push(data)}save();closeModal();refresh();toast('Data buku berhasil disimpan.')};$('#cancelModal').onclick=closeModal}
function loanForm(){let availableBooks=db.books.filter(b=>available(b)>0);showModal('Catat Peminjaman','Pilih buku yang tersedia dan masukkan data siswa.',`<form id="loanForm"><div class="form-grid"><div class="form-field full"><label>Buku</label><select name="bookId" required>${availableBooks.map(b=>`<option value="${b.id}">${esc(b.title)} — tersedia ${available(b)}</option>`).join('')}</select></div><div class="form-field"><label>Nama Siswa</label><input name="student" required placeholder="Nama lengkap"></div><div class="form-field"><label>Kelas</label><input name="className" required placeholder="Contoh: VIII A"></div><div class="form-field"><label>Tanggal Pinjam</label><input name="date" type="date" required value="${today()}"></div><div class="form-field"><label>Jatuh Tempo</label><input name="due" type="date" required value="${new Date(Date.now()+7*86400000).toISOString().slice(0,10)}"></div></div><div class="modal-actions"><button type="button" class="btn btn-light" id="cancelModal">Batal</button><button class="btn btn-primary">Simpan Peminjaman</button></div></form>${availableBooks.length?'':'<div class="empty">Semua buku sedang tidak tersedia.</div>'}`);$('#loanForm')?.addEventListener('submit',e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));db.loans.push({id:'L'+String(Date.now()).slice(-4),...data,returned:false,returnDate:''});save();closeModal();refresh();toast('Peminjaman berhasil dicatat.')});$('#cancelModal').onclick=closeModal}
function returnLoan(id){let l=db.loans.find(x=>x.id===id);if(!l||l.returned)return;showModal('Konfirmasi Pengembalian','Pastikan buku sudah diterima kembali.',`<div class="panel" style="box-shadow:none;border:1px solid var(--line);margin-bottom:15px"><div style="padding:15px"><b>${esc(bookById(l.bookId)?.title||'-')}</b><div class="book-sub">${esc(l.student)} • ${esc(l.className)}</div></div></div><div class="modal-actions"><button class="btn btn-light" id="cancelModal">Batal</button><button class="btn btn-primary" id="confirmReturn">Ya, Kembalikan</button></div>`);$('#cancelModal').onclick=closeModal;$('#confirmReturn').onclick=()=>{l.returned=true;l.returnDate=today();save();closeModal();refresh();toast('Pengembalian berhasil diproses.')}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2400)}
function go(page){$$('.page').forEach(p=>p.classList.remove('active'));$('#'+page+'Page').classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent={dashboard:'Dashboard',books:'Data Buku',loans:'Peminjaman',returns:'Pengembalian'}[page];$('#sidebar').classList.remove('open')}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-page-link]').forEach(b=>b.onclick=()=>go(b.dataset.pageLink));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalClose').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#addBookBtn').onclick=()=>bookForm();$('#quickAddBtn').onclick=()=>{go('books');bookForm()};$('#addLoanBtn').onclick=loanForm;
$('#bookSearch').oninput=renderBooks;$('#bookCategoryFilter').onchange=renderBooks;$('#loanSearch').oninput=renderLoans;$('#loanStatusFilter').onchange=renderLoans;
document.addEventListener('click',e=>{let eb=e.target.closest('[data-edit-book]'),dbtn=e.target.closest('[data-delete-book]'),ret=e.target.closest('[data-return]');if(eb)bookForm(bookById(eb.dataset.editBook));if(dbtn){let b=bookById(dbtn.dataset.deleteBook);if(!b)return;if(db.loans.some(l=>l.bookId===b.id&&!l.returned))return toast('Buku masih sedang dipinjam.');if(confirm('Hapus buku ini dari inventaris?')){db.books=db.books.filter(x=>x.id!==b.id);save();refresh();toast('Buku dihapus.')}}if(ret)returnLoan(ret.dataset.return)});
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='database-perpustakaan.json';a.click();URL.revokeObjectURL(a.href);toast('Data berhasil diekspor.');};
refresh();
